name: Action Test

on:
    push:
      tags:
        - '*'
permissions:
  contents: write

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: m0nsterrr/git-cliff-action@v1.7.0
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Create release
        run: gh release create ${{ github.ref_name }} -F git-cliff/CHANGELOG.md --draft
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
